name: risha_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  fpdart: ^1.1.0
  flutter_svg: ^2.0.11
  flutter_animate: ^4.5.0
  flutter_native_splash: ^2.4.0
  shimmer: ^3.0.0
  get: ^5.0.0-release-candidate-9.2.1
  flutter_screenutil: ^5.9.3
  flutter_local_notifications: ^17.2.4
  dropdown_button2: ^2.3.9
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  cached_network_image: ^3.4.1
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  connectivity_plus: ^6.0.5
  dio: ^5.7.0
  retry: ^3.1.2
  readmore: ^3.0.0
  photo_view: ^0.15.0
  lottie: ^3.1.2
  intl: ^0.19.0
  onesignal_flutter: ^5.2.6
  blur: ^4.0.0
  url_launcher: ^6.3.1
  timezone: ^0.9.4
  device_preview: ^1.2.0
  easy_localization: ^3.0.7
  in_app_review: ^2.0.9
  app_links: ^6.3.2
  pinput: ^5.0.0
  flutter_spinkit: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svgs/
    - assets/animations/
    - assets/translations/en.json
    - assets/translations/ar.json